M48
; DRILL file {KiCad 7.0.8-7.0.8~ubuntu20.04.1} date 2023년 10월 05일 (목) 오후 05시 37분 35초
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-05T17:37:35+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8-7.0.8~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0630
%
G90
G05
T1
X0.1181Y1.2579
X0.1181Y0.8642
T0
M30
